# Generated by Django 4.2 on 2023-04-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_guardians'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guardian',
        ),
    ]
