# Generated by Django 4.2 on 2023-04-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_delete_guardian'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
