# Generated by Django 4.2 on 2023-04-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=20)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
