# Generated by Django 4.2 on 2023-04-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('marks', models.FloatField()),
            ],
        ),
    ]
